kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: RB-$NAMESPACE
  namespace: openshift
subjects:
  - kind: ServiceAccount
    name: pipelineprocesstemplate
    namespace: $NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline
